# Generated by Django 4.1.3 on 2022-11-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
